CREATE TABLE "BASE_ANALYSIS_SENTIMENT" 
   (	"ID" NUMBER(12,0) NOT NULL ENABLE, 
	"NAME" VARCHAR2(200 BYTE) NOT NULL ENABLE, 
	"KEY_WORD" VARCHAR2(200 BYTE) NOT NULL ENABLE, 
	"DICT_ENABLED_VALUE" NUMBER(20,0), 
	"DICT_ENABLED_NAME" VARCHAR2(100 BYTE), 
	 CONSTRAINT "PK_ANAL_SENTIMENT" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT);
 

   COMMENT ON COLUMN "BASE_ANALYSIS_SENTIMENT"."ID" IS '主键';
 
   COMMENT ON COLUMN "BASE_ANALYSIS_SENTIMENT"."NAME" IS '监测名称';
 
   COMMENT ON COLUMN "BASE_ANALYSIS_SENTIMENT"."KEY_WORD" IS '监测关键字';
 
   COMMENT ON COLUMN "BASE_ANALYSIS_SENTIMENT"."DICT_ENABLED_VALUE" IS '状态值';
 
   COMMENT ON COLUMN "BASE_ANALYSIS_SENTIMENT"."DICT_ENABLED_NAME" IS '状态名';
 
   COMMENT ON TABLE "BASE_ANALYSIS_SENTIMENT"  IS '舆情配置';

	insert into BASE_ANALYSIS_SENTIMENT(ID,NAME,KEY_WORD,DICT_ENABLED_VALUE,DICT_ENABLED_NAME) values(1,'户户通','户户通,恶意,安装',300010000000001,'未删除');
	insert into BASE_ANALYSIS_SENTIMENT(ID,NAME,KEY_WORD,DICT_ENABLED_VALUE,DICT_ENABLED_NAME) values(2,'户户通1','户户通1,恶意1,安装1',300010000000002,'删除');


  CREATE TABLE "BASE_ANALYSIS_SENTIMENT_DETAIL" 
   (	"ID" NUMBER(18,0) NOT NULL ENABLE, 
	"NAME" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	"KEY_WORD" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	"TITLE" VARCHAR2(150 BYTE), 
	"INTRODUCTION" VARCHAR2(2000 BYTE), 
	"MAIN_WORD" VARCHAR2(100 BYTE), 
	"ORIGIN_VALUE" NUMBER(20,0), 
	"ORIGIN_NAME" VARCHAR2(100 BYTE), 
	"OCCUR_TIME" TIMESTAMP (6), 
	"URL" VARCHAR2(500 BYTE), 
	"PID" NUMBER(18,0), 
	 CONSTRAINT "PK_ANAL_SENTIMENT_DETAIL" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT);
 

   COMMENT ON COLUMN "BASE_ANALYSIS_SENTIMENT_DETAIL"."ID" IS '主键';
 
   COMMENT ON COLUMN "BASE_ANALYSIS_SENTIMENT_DETAIL"."NAME" IS '监控名称';
 
   COMMENT ON COLUMN "BASE_ANALYSIS_SENTIMENT_DETAIL"."KEY_WORD" IS '监控关键字';
 
   COMMENT ON COLUMN "BASE_ANALYSIS_SENTIMENT_DETAIL"."TITLE" IS '文章标题';
 
   COMMENT ON COLUMN "BASE_ANALYSIS_SENTIMENT_DETAIL"."INTRODUCTION" IS '文章简介';
 
   COMMENT ON COLUMN "BASE_ANALYSIS_SENTIMENT_DETAIL"."MAIN_WORD" IS '主题词';
 
   COMMENT ON COLUMN "BASE_ANALYSIS_SENTIMENT_DETAIL"."ORIGIN_VALUE" IS '来源类型';
 
   COMMENT ON COLUMN "BASE_ANALYSIS_SENTIMENT_DETAIL"."ORIGIN_NAME" IS '来源类型名';
 
   COMMENT ON COLUMN "BASE_ANALYSIS_SENTIMENT_DETAIL"."OCCUR_TIME" IS '时间';
 
   COMMENT ON COLUMN "BASE_ANALYSIS_SENTIMENT_DETAIL"."URL" IS '网址';
 
   COMMENT ON COLUMN "BASE_ANALYSIS_SENTIMENT_DETAIL"."PID" IS '舆情ID';




CREATE TABLE "TEST02" 
   (  "ID" NUMBER(12,0) NOT NULL ENABLE, 
  "NAME" VARCHAR2(200 BYTE) NOT NULL ENABLE);


CREATE SEQUENCE BASE_ANALYSIS_SENTIMENT_DETAIL_sequence
INCREMENT BY 1 -- 每次加几个
START WITH 1 -- 从1开始计数
NOMAXVALUE -- 不设置最大值
NOCYCLE -- 一直累加，不循环
NOCACHE -- 不建缓冲区